"""Add CustomerFollowUp table and relationship with SampleCustomer

Revision ID: 1497635b4441
Revises: 6d73bb690ce7
Create Date: 2025-04-23 21:44:33.906643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1497635b4441'
down_revision: Union[str, None] = '6d73bb690ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_time', sa.DateTime(), nullable=False),
    sa.Column('follow_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_contact_time', sa.DateTime(), nullable=True),
    sa.Column('follow_up_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sample_customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_customer_id'], ['sample_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_follow_ups_contact_time'), 'customer_follow_ups', ['contact_time'], unique=False)
    op.create_index(op.f('ix_customer_follow_ups_sample_customer_id'), 'customer_follow_ups', ['sample_customer_id'], unique=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_customer_follow_ups_sample_customer_id'), table_name='customer_follow_ups')
    op.drop_index(op.f('ix_customer_follow_ups_contact_time'), table_name='customer_follow_ups')
    op.drop_table('customer_follow_ups')
    # ### end Alembic commands ###
