"""Add level and created_by_id to Role model

Revision ID: 6d73bb690ce7
Revises: 
Create Date: 2025-04-12 17:55:48.394961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d73bb690ce7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_hierarchy')
    op.add_column('roles', sa.Column('level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('roles', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_level'), 'roles', ['level'], unique=False)
    op.create_foreign_key(None, 'roles', 'users', ['created_by_id'], ['id'])
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_level'), table_name='roles')
    op.drop_column('roles', 'created_by_id')
    op.drop_column('roles', 'level')
    op.create_table('role_hierarchy',
    sa.Column('ancestor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descendant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['roles.id'], name='role_hierarchy_ancestor_id_fkey'),
    sa.ForeignKeyConstraint(['descendant_id'], ['roles.id'], name='role_hierarchy_descendant_id_fkey'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id', name='role_hierarchy_pkey')
    )
    # ### end Alembic commands ###
